language: java

before_install:
   docker buildx build .
  - sudo add-apt-repository ppa:linuxuprising/java
  - sudo apt-get update
  - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - sudo apt-get install -y oracle-java8-installer
  - sudo apt-get install -y oracle-java8-set-default

env:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle

script:
  - echo "Starting build..."
  - ./gradlew clean jar
  - echo "Build completed."

before_script:
  - echo 'Testing coming soon'
