language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew clean jar   # Build the jar files
  - ./gradlew test        # Execute unit tests

after_success:
  - echo "Build and tests passed!"

notifications:
  email:
    on_success: always
    on_failure: always
