language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew clean jar
  - ./gradlew test
  - ./gradlew jacocoTestReport # Generate the coverage report

after_success:
  # Validate coverage
  - bash <(curl -s https://coverage.example.com/coverage-check.sh)

deploy:
  provider: script
  script: bash <(curl -s https://example.com/stub-deploy.sh) # Stub deployment
  on:
    branch: main
